version: "3"
services:
  mysqldb-auth:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      -  mysqldb-auth
    env_file:
      - .env
    environment:
      PORT: ":8080"
      DB_URL: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysqldb-auth:3306)/${MYSQL_DATABASE}"


volumes:
  db-data:

